# docker-compose.yml
services:
  samba:
    container_name: nas-samba
    build:
      context: samba
    restart: unless-stopped
    labels:
      autoheal: true
    volumes:
      - type: bind
        source: /data/nas/family
        target: /data/family
      - type: bind
        source: /data/nas/users
        target: /home
      - type: bind
        source: /data/nas/windows_backup
        target: /data/windows_backup
      - type: volume
        source: samba-data
        target: /var/lib/samba
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    network_mode: host
  nginx:
    container_name: nas-nginx
    build:
      context: nginx
    restart: unless-stopped
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - nas
    ports:
      - "80:80"
  nextcloud:
    container_name: nas-nextcloud
    build:
      context: nextcloud
    restart: unless-stopped
    labels:
      autoheal: true
    volumes:
      - type: bind
        source: /data/nas/nextcloud
        target: /var/www/html
      - type: bind
        source: /data/nas/users/ashish
        target: /var/www/html/data/ashish/files
      - type: bind
        source: /data/nas/users/melvin
        target: /var/www/html/data/melvin/files
      - type: bind
        source: /data/nas/users/joy
        target: /var/www/html/data/joy/files
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - nas
  web:
    container_name: nas-web
    build:
      context: web
    restart: unless-stopped
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - nas
  scraper:
    container_name: nas-scraper
    build:
      context: scraper
    restart: unless-stopped
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - nas
  redis:
    container_name: nas-redis
    image: redis
    restart: unless-stopped
    volumes:
      - type: volume
        source: redis-data
        target: /data
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - nas
  postgres:
    container_name: nas-postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    networks:
      - nas

volumes:
  redis-data:
    name: nas-redis-data
    external: true
  postgres-data:
    name: nas-postgres-data
    external: true
  samba-data:
    name: nas-samba-data
    external: true

networks:
  nas:
    name: nas
    ipam:
      config:
        - subnet: 172.18.1.0/24
          gateway: 172.18.1.1
